fix: Verify deploy.sh existence and accessibility
This commit adds a step to verify that the deploy.sh script exists and is accessible on the server before attempting deployment. The changes include:

1. Added a new step "Verify SSH connection and check deploy.sh" in the GitHub Actions workflow.
2. This step uses SSH to connect to the server and check if /home/viko/deploy.sh exists.
3. If the file is not found, the workflow will fail, preventing further steps from executing.

This ensures that the deployment process will only proceed if the necessary script is in place, reducing the risk of failed deployments due to missing files.

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -13,6 +13,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: List files
+        run: ls -la  # Verifica que deploy.sh esté presente
+
+      - name: Verify SSH connection and check deploy.sh
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'if [ -f /home/viko/deploy.sh ]; then echo "deploy.sh found"; else echo "deploy.sh not found"; exit 1; fi'
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
@@ -37,6 +44,3 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}  # Clave privada SSH
           source: "deploy.sh"  # Asegúrate de que esta ruta sea correcta
           target: "/home/viko/deploy.sh"  # Ruta en el servidor
-
-      - name: Execute Deployment Script
-        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'bash /home/viko/deploy.sh'
